name: Checkout Custom Actions
description: Checkout a custom CI/CD actions repository

inputs:
  actions_repository:
    description: 'Repository of the CI/CD actions to use. Requires GH_TOKEN to be set as a job-level env var for private repositories.'
  actions_ref:
    description: 'Branch or tag of the CI/CD actions to use'
    default: 'main'

runs:
  using: "composite"
  
  steps:
    - name: Checkout Custom Actions
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.actions_repository }}
        ref: ${{ inputs.actions_ref }}
        path: ./custom-actions
        token: ${{ env.GH_TOKEN }}
    
    # Move the custom CI/CD actions to the actions directory so they can be referenced with relative paths
    - name: Move Actions
      shell: bash
      run: |
        mkdir -p ./actions
        mv ./custom-actions/actions/* ./actions/