name: Checkout Repo
description: Checkout the repository code for the workflow and optional custom CI/CD actions

inputs:
  ref_name:
    description: 'Name of the branch or tag to checkout (e.g.: github.ref_name)'
    required: true
  cicd_repo:
    description: 'Repository of the CI/CD actions to use'
    default: ''
    required: false
  cicd_ref:
    description: 'Branch or tag of the CI/CD actions to use'
    default: 'main'
    required: false
  actions_temp_path:
    description: 'Path to checkout the custom CI/CD actions to, before moving them to the actions directory for the current workflow'
    default: 'cicd-repo'
    required: false

runs:
  using: "composite"
  
  steps:
    # Check out the actual repository code
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.ref_name }}
    
    # Check out the custom CI/CD actions
    - name: Checkout CI/CD Actions
      uses: actions/checkout@v4
      if: ${{ inputs.cicd_repo != '' }}
      with:
        repository: ${{ inputs.cicd_repo }}
        ref: ${{ inputs.cicd_ref }}
        path: ./${{ inputs.actions_temp_path }}

    # Move the custom CI/CD actions to the actions directory so they can be referenced with relative paths
    - name: Move Actions
      shell: bash
      if: ${{ inputs.cicd_repo != '' }}
      run: |
        mkdir -p ./actions
        mv ./${{ inputs.actions_temp_path }}/actions/* ./actions/